import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Link from 'next/link';
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Image Analysis App",
  description: "Generated by create next app",
};

// A simple Nav component
function NavBar() {
  return (
    <nav className="bg-white shadow-md">
      <div className="container mx-auto px-4">
        <div className="flex justify-between items-center py-4">
          <Link href="/" className="text-2xl font-bold text-indigo-600">
            ImageApp
          </Link>
          <div className="flex space-x-6">
            <Link href="/" className="text-gray-600 hover:text-indigo-500 transition-colors">
              Gallery
            </Link>
            <Link href="/batches" className="text-gray-600 hover:text-indigo-500 transition-colors">
              Batches
            </Link>
          </div>
        </div>
      </div>
    </nav>
  );
}


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <NavBar />
        {children}
      </body>
    </html>
  );
}