# In alembic/versions/b8c2e1c76ce3_add_thumbnail.py

"""Initial migration to create tables

Revision ID: b8c2e1c76ce3
Revises: 
Create Date: 2025-08-18 15:00:00.123456

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b8c2e1c76ce3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('original_filename', sa.String(length=1024), nullable=False),
    sa.Column('file_path', sa.String(length=1024), nullable=False),
    sa.Column('file_size', sa.BigInteger(), nullable=True),
    sa.Column('mime_type', sa.String(length=255), nullable=True),
    sa.Column('has_thumbnail', sa.Boolean(), nullable=True),
    sa.Column('features', sa.LargeBinary(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('file_path'),
    sa.UniqueConstraint('filename'),
    schema='image_clustering'
    )
    op.create_table('clustering_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.String(length=255), nullable=False),
    sa.Column('image_id', sa.Integer(), nullable=False),
    sa.Column('cluster_label', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['image_id'], ['image_clustering.images.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='image_clustering'
    )
    op.create_index('idx_clustering_results_run_id', 'clustering_results', ['run_id'], unique=False, schema='image_clustering')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_clustering_results_run_id', table_name='clustering_results', schema='image_clustering')
    op.drop_table('clustering_results', schema='image_clustering')
    op.drop_table('images', schema='image_clustering')
    # ### end Alembic commands ###