"""Add missing columns to images table

Revision ID: c69c13026fe2
Revises: ba650b8c5046
Create Date: 2025-08-24 01:10:23.722732

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c69c13026fe2'
down_revision: Union[str, Sequence[str], None] = 'ba650b8c5046'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('images', sa.Column('file_size', sa.BigInteger(), nullable=True), schema='image_clustering')
    op.add_column('images', sa.Column('mime_type', sa.String(length=255), nullable=True), schema='image_clustering')
    op.add_column('images', sa.Column('has_thumbnail', sa.Boolean(), nullable=True), schema='image_clustering')
    op.add_column('images', sa.Column('features', sa.LargeBinary(), nullable=True), schema='image_clustering')
    op.add_column('images', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True), schema='image_clustering')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('images', 'created_at', schema='image_clustering')
    op.drop_column('images', 'features', schema='image_clustering')
    op.drop_column('images', 'has_thumbnail', schema='image_clustering')
    op.drop_column('images', 'mime_type', schema='image_clustering')
    op.drop_column('images', 'file_size', schema='image_clustering')
    # ### end Alembic commands ###
