"""Add Image Hash

Revision ID: f20a4b6a74f4
Revises: bb0ac39a2a27
Create Date: 2025-08-19 15:22:54.271735

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f20a4b6a74f4'
down_revision: Union[str, Sequence[str], None] = 'bb0ac39a2a27'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('images', sa.Column('image_hash', sa.String(length=255), nullable=False), schema='image_clustering')
    op.create_unique_constraint(None, 'images', ['image_hash'], schema='image_clustering')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'images', schema='image_clustering', type_='unique')
    op.drop_column('images', 'image_hash', schema='image_clustering')
    # ### end Alembic commands ###
